trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @antora/cli@2.0 -g @antora/site-generator-default@2.0 firebase-tools
  displayName: 'Install Antora'

- script: |
    antora site.yml --stacktrace
  displayName: 'Generate Site'

- script: |
    firebase use "$(firebaseProject)" --token "$(firebaseDeployKey)"
    firebase deploy --token "$(firebaseDeployKey)" --only hosting -m "CI Build"
  displayName: 'Deploy Site'