---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh
  namespace: openshift-operators
spec:
  channel: stable
  source: redhat-operators-packages
  name: servicemeshoperator 
  sourceNamespace: openshift-operators